# Generated by Django 4.2.29 on 2026-03-15 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lightrag_app", "0003_remove_workspace_created_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChunkConfig",
        ),
    ]
