# Generated by Django 4.2.29 on 2026-03-15 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lightrag_app", "0003_rename_documentstatus_fields"),
        ("lightrag_app", "0004_delete_chunkconfig"),
    ]

    operations = []
