# Generated by Codex on 2026-03-15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lightrag_app", "0005_merge_20260315_2144"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="file_paths",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="file_paths",
        ),
    ]
