# Generated by Django 4.2.29 on 2026-03-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lightrag_app", "0007_remove_documentstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorembedding",
            name="vector_type",
            field=models.CharField(
                choices=[
                    ("entity", "Entity"),
                    ("relation", "Relation"),
                    ("document", "Document"),
                ],
                max_length=20,
            ),
        ),
    ]
