# Generated by Django 4.2.29 on 2026-03-14 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheEntry",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("llm_response", "LLM Response"),
                            ("embedding", "Embedding"),
                            ("entity_extraction", "Entity Extraction"),
                            ("relation_extraction", "Relation Extraction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cache_key", models.CharField(max_length=1000)),
                ("cache_value", models.JSONField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_cache",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "track_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("chunks_count", models.IntegerField(default=0)),
                ("chunks_list", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_document_status",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                ("entity_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                ("file_paths", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_entities",
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("relation_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                ("file_paths", models.JSONField(blank=True, default=list)),
                ("weight", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="lightrag_app.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="lightrag_app.entity",
                    ),
                ),
            ],
            options={
                "db_table": "lightrag_relations",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lightrag_workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VectorEmbedding",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "vector_type",
                    models.CharField(
                        choices=[
                            ("entity", "Entity"),
                            ("relation", "Relation"),
                            ("chunk", "Chunk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.CharField(max_length=255)),
                ("embedding", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_vector_embeddings",
                "indexes": [
                    models.Index(
                        fields=["vector_type", "content_id"],
                        name="lightrag_ve_vector__502ff1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TextChunk",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("tokens", models.IntegerField()),
                ("chunk_order_index", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="lightrag_app.document",
                    ),
                ),
            ],
            options={
                "db_table": "lightrag_text_chunks",
                "ordering": ["document", "chunk_order_index"],
            },
        ),
        migrations.CreateModel(
            name="RelationChunk",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_chunks",
                        to="lightrag_app.textchunk",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_chunks",
                        to="lightrag_app.relation",
                    ),
                ),
            ],
            options={
                "db_table": "lightrag_relation_chunks",
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("document_ingestion", "Document Ingestion"),
                            ("entity_extraction", "Entity Extraction"),
                            ("relation_extraction", "Relation Extraction"),
                            ("embedding_generation", "Embedding Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("progress", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_processing_jobs",
                "indexes": [
                    models.Index(
                        fields=["job_type"], name="lightrag_pr_job_typ_05e2fa_idx"
                    ),
                    models.Index(
                        fields=["status"], name="lightrag_pr_status_ba99fc_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="lightrag_pr_created_c28326_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityChunk",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_chunks",
                        to="lightrag_app.textchunk",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_chunks",
                        to="lightrag_app.entity",
                    ),
                ),
            ],
            options={
                "db_table": "lightrag_entity_chunks",
            },
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["name"], name="lightrag_en_name_64e665_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["entity_type"], name="lightrag_en_entity__4c95f4_idx"
            ),
        ),
        migrations.AddField(
            model_name="documentstatus",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="lightrag_app.document",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["track_id"], name="lightrag_do_track_i_d1a94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cacheentry",
            index=models.Index(
                fields=["cache_type"], name="lightrag_ca_cache_t_95923e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cacheentry",
            index=models.Index(
                fields=["expires_at"], name="lightrag_ca_expires_70d2fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cacheentry",
            unique_together={("cache_key",)},
        ),
        migrations.AddIndex(
            model_name="textchunk",
            index=models.Index(
                fields=["document"], name="lightrag_te_documen_0ef383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationchunk",
            index=models.Index(
                fields=["relation"], name="lightrag_re_relatio_7eebdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationchunk",
            index=models.Index(fields=["chunk"], name="lightrag_re_chunk_i_9898d0_idx"),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["source_entity", "target_entity"],
                name="lightrag_re_source__d06e92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["relation_type"], name="lightrag_re_relatio_2fe727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychunk",
            index=models.Index(
                fields=["entity"], name="lightrag_en_entity__336681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychunk",
            index=models.Index(fields=["chunk"], name="lightrag_en_chunk_i_a0528f_idx"),
        ),
        migrations.AddIndex(
            model_name="documentstatus",
            index=models.Index(fields=["status"], name="lightrag_do_status_a42f72_idx"),
        ),
    ]
