# Generated by Django 4.2.29 on 2026-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lightrag_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkConfig",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("semantic", "Semantic Chunker"),
                            ("recursive", "Recursive Character Splitter"),
                            ("fixed_size", "Fixed Size Chunker"),
                            ("token_based", "Token Based Chunker"),
                        ],
                        default="semantic",
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration parameters for the chunking strategy",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_chunk_configs",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["strategy"], name="lightrag_ch_strateg_eb5d37_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="lightrag_ch_is_defa_eb812c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="lightrag_ch_is_acti_7caa42_idx"
                    ),
                ],
            },
        ),
    ]
