# Generated by Django 4.2.29 on 2026-03-15 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lightrag_app", "0002_chunk_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="chunkconfig",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="chunkconfig",
            name="lightrag_ch_strateg_eb5d37_idx",
        ),
        migrations.RemoveIndex(
            model_name="chunkconfig",
            name="lightrag_ch_is_defa_eb812c_idx",
        ),
        migrations.RemoveIndex(
            model_name="chunkconfig",
            name="lightrag_ch_is_acti_7caa42_idx",
        ),
        migrations.RemoveField(
            model_name="chunkconfig",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="chunkconfig",
            name="name",
        ),
        migrations.AlterModelTable(
            name="chunkconfig",
            table=None,
        ),
        migrations.DeleteModel(
            name="Workspace",
        ),
    ]
