# Generated by Django 6.0.3 on 2026-03-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheEntry",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("llm_response", "LLM Response"),
                            ("embedding", "Embedding"),
                            ("entity_extraction", "Entity Extraction"),
                            ("relation_extraction", "Relation Extraction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cache_key", models.CharField(max_length=1000)),
                ("cache_value", models.JSONField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_cache",
                "indexes": [
                    models.Index(
                        fields=["cache_type"], name="lightrag_ca_cache_t_95923e_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="lightrag_ca_expires_70d2fd_idx"
                    ),
                ],
                "unique_together": {("cache_key",)},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "track_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_documents",
                "indexes": [
                    models.Index(
                        fields=["track_id"], name="lightrag_do_track_i_d1a94c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                ("entity_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_entities",
                "indexes": [
                    models.Index(fields=["name"], name="lightrag_en_name_64e665_idx"),
                    models.Index(
                        fields=["entity_type"], name="lightrag_en_entity__4c95f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("document_ingestion", "Document Ingestion"),
                            ("entity_extraction", "Entity Extraction"),
                            ("relation_extraction", "Relation Extraction"),
                            ("embedding_generation", "Embedding Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("progress", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_processing_jobs",
                "indexes": [
                    models.Index(
                        fields=["job_type"], name="lightrag_pr_job_typ_05e2fa_idx"
                    ),
                    models.Index(
                        fields=["status"], name="lightrag_pr_status_ba99fc_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="lightrag_pr_created_c28326_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VectorEmbedding",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "vector_type",
                    models.CharField(
                        choices=[
                            ("entity", "Entity"),
                            ("relation", "Relation"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.CharField(max_length=255)),
                ("embedding", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lightrag_vector_embeddings",
                "indexes": [
                    models.Index(
                        fields=["vector_type", "content_id"],
                        name="lightrag_ve_vector__502ff1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("relation_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                ("weight", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="core.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "lightrag_relations",
                "indexes": [
                    models.Index(
                        fields=["source_entity", "target_entity"],
                        name="lightrag_re_source__d06e92_idx",
                    ),
                    models.Index(
                        fields=["relation_type"], name="lightrag_re_relatio_2fe727_idx"
                    ),
                ],
            },
        ),
    ]
